services:
    form.type.role_menu:
        class: Bigfoot\Bundle\UserBundle\Form\BigfootRoleMenuType
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: bigfootrolemenutype }

    # Kernel Listener
    bigfoot_user.listener.kernel:
        class: Bigfoot\Bundle\UserBundle\Listener\KernelListener
        arguments:
            - @security.context
            - @stof_doctrine_extensions.listener.translatable
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }

    # Menu Subscriber
    bigfoot_user.subscriber.menu:
        class: Bigfoot\Bundle\UserBundle\Subscriber\MenuSubscriber
        arguments:
            - @security.context
        tags:
            - { name: kernel.event_subscriber }

    # User Manager
    bigfoot_user.manager.user:
        class: Bigfoot\Bundle\UserBundle\Manager\UserManager
        arguments:
            - @doctrine.orm.entity_manager
            - @security.encoder_factory
            - @security.user_checker
            - @security.context
            - @session
            - @translator
            - @bigfoot_context
            - @bigfoot_user.mailer.user
            - @bigfoot_core.generator.token
        calls:
            - [setRequest, ['@?request=']]

    # User Mailer
    bigfoot_user.mailer.user:
        class: Bigfoot\Bundle\UserBundle\Mailer\UserMailer
        parent: bigfoot_core.mailer.abstract

    # User Subscriber
    bigfoot_user.subscriber.user:
        class: Bigfoot\Bundle\UserBundle\Subscriber\UserSubscriber
        arguments:
            - @bigfoot_user.manager.user
        tags:
            - { name: kernel.event_subscriber }

    # User Type
    bigfoot_user.form.type.user:
        class: Bigfoot\Bundle\UserBundle\Form\Type\UserType
        arguments:
            - @security.context
            - %bigfoot_core.languages.front%
        tags:
            - { name: form.type, alias: bigfoot_user }

    # Login Type
    bigfoot_user.form.type.login:
        class: Bigfoot\Bundle\UserBundle\Form\Type\LoginType
        tags:
            - { name: form.type, alias: bigfoot_login }

    # ForgotPassword Type
    bigfoot_user.form.type.forgot_password:
        class: Bigfoot\Bundle\UserBundle\Form\Type\ForgotPasswordType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: bigfoot_forgot_password }

    # ResetPassword Type
    bigfoot_user.form.type.reset_password:
        class: Bigfoot\Bundle\UserBundle\Form\Type\ResetPasswordType
        tags:
            - { name: form.type, alias: bigfoot_reset_password }

    # Role Type
    bigfoot_user.form.type.role:
        class: Bigfoot\Bundle\UserBundle\Form\Type\RoleType
        tags:
            - { name: form.type, alias: bigfoot_role }